server:
    port: 8091
    address: localhost

logging:
  level:
    org:
      springframework:
        data:
          elasticsearch: DEBUG  # To show the search query

spring:
    datasource:
        url: jdbc:log4jdbc:mysql://127.0.0.1:3306/myproject?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
        username: root
        password: root
        driver-class-name: net.sf.log4jdbc.DriverSpy
    thymeleaf:
      cache: false

flyway:
  url: jdbc:mysql://127.0.0.1:3306/myproject?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
  user: root
  password: root
  validateOnMigrate: false  # ignore flyway validation
  baselineOnMigrate: true






