server:
    port: 8090
    address: localhost
    compression:
      enabled: true

logging:
  level:
    org:
      springframework:
        data:
          elasticsearch: DEBUG  # To show the search query

spring:
    datasource:
        url: jdbc:log4jdbc:mysql://127.0.0.1:3306/myproject?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull
        username: root
        password: root
        driver-class-name: net.sf.log4jdbc.DriverSpy
    thymeleaf:
      cache: false
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
    jackson:
      serialization: true
    data:
      rest:
        base-path: /api
     # Redis配置
    redis:
      host: 127.0.0.1
      port: 6379
      password:
         # 连接超时时间（毫秒）
      timeout: 10000
      pool:
        max-idle: 20
        min-idle: 5
        max-active: 20
        max-wait: 2
    activemq:
      broker-url: tcp://localhost:61616
      in-memory: true
      pool:
        enabled: false

flyway:
  url: jdbc:mysql://127.0.0.1:3306/myproject?useUnicode=true&useSSL=false&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
  user: root
  password: root
  validateOnMigrate: false  # ignore flyway validation
  baselineOnMigrate: true






