server:
    port: 8090
    address: localhost
    compression:
      enabled: true

logging:
  config: classpath:logback-spring.xml
spring:
    datasource:
        url: jdbc:log4jdbc:mysql://127.0.0.1:3306/myproject?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&zeroDateTimeBehavior=convertToNull
        username: root
        password: root
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    thymeleaf:
      cache: false
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
    jackson:
      serialization: true
    data:
      rest:
        base-path: /api
     # Redis配置
    redis:
      host: 127.0.0.1
      port: 6379
      password:
     # 连接超时时间（毫秒）
      timeout: 10000
      pool:
        max-idle: 20
        min-idle: 5
        max-active: 20
        max-wait: 2
    activemq:
      broker-url: tcp://localhost:61616
      in-memory: true
      pool:
        enabled: false
     # 404 交给异常处理器处理
    mvc:
      throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false
      static-locations: classpath:/static/
    mail:
      host: smtp.houbank.cn
      username: ENC(TQfGGjZ5dOcXBs69q7Fn3xKOjf86loiYur4QOQ12jVs=)
      password: ENC(MwfRmZnTLxdK6Jslst6XBfPaFnAorXYC)

flyway:
  url: jdbc:mysql://127.0.0.1:3306/myproject?useUnicode=true&useSSL=false&characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
  user: root
  password: root
  validateOnMigrate: false  # ignore flyway validation
  baselineOnMigrate: true

 # redisson lock
redisson:
   address: redis://127.0.0.1:6379

jasypt:
  encryptor:
    password: e!Jd&ljyJ^e4I5oU







