-- 用户
CREATE TABLE IF NOT EXISTS `user`(
  id BIGINT NOT NULL AUTO_INCREMENT,
  username VARCHAR(50),
  PASSWORD VARCHAR(50),
  STATUS INTEGER,
  descn VARCHAR(200),
  PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

